### PR TITLE
README.md: add snapshots

### PR DESCRIPTION
**Pull request by mrubli**
I figured this was such a useful node that it was a shame not to have a screenshot or two to illustrate how to use it. 😄

### CODE REVIEW

**Comment by iurly** [comment]
Thank you @mrubli! I'm glad it turned out useful to you as well, and thank you for going through the trouble to add the screenshots!
Just one (naive) question: why did you use `const prettyDuration = function(last)` instead of a simpler `function prettyDuration(last)`?
If it comes from the days where you had to store/retrieve the common functions to/from global or flow context, then perhaps this should be simplified, don't you think?

**Comment by mrubli** [comment]
I think that may just have been a C++ habit that slipped in because it used to be nested inside another function while I was testing something. I'll update the screenshot later today. Thanks for pointing that out!

**Comment by mrubli** [comment]
Done!

By the way, have you considered uploading this module to npm and the Node-RED Library? It would be both easier to find and install that way.

**Comment by iurly** [comment]
Thanks! This was indeed meant to be a prototype to be discussed on the forum, but I never pushed enough so to get some feedback. Might be worth proposing it again though.

**Pull request merged**
